spring:
  application:
    name: foodService

  datasource:
    url: jdbc:mysql://localhost:3306/lcwd
    username: root
    password: "{cipher}9c63b98e03c08fc1ce2f2c27150e344ddcc3d684fe2f80bf3d719eae8beb9cbc"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
 # Enables all the actuator endpoints.
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

server:
  port: 9092
