spring:
  application:
    name: userService

  datasource:
    url: jdbc:mysql://localhost:3306/lcwd
    username: root
    password: Restinpeace11.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9093
